#  NUMPY LIBRARY

In [1]:
#Import Numpy Library
import numpy as np

In [2]:
# create simple array from the list

arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr.ndim #dimention

2

In [4]:
arr.shape #shape of array

(2, 4)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.data #memory location

# RANDOM NUMBER GENERATOR

In [7]:
#IMPORT NUMPY LIBRARY
import numpy as np
from numpy import random

In [11]:
x=random.randint(1000)
x

228

In [13]:
x=random.rand(10)
x

array([0.45338992, 0.93328055, 0.57196643, 0.29911347, 0.79724806,
       0.97662495, 0.61868369, 0.7795701 , 0.94548171, 0.89223444])

In [15]:
x=random.randint(5)
x

1

In [19]:
x=random.randint(100, size=(5))
x

array([97, 63, 23, 57, 72])

In [20]:
x=random.randint(100, size=(5,3))
x

array([[36, 53, 54],
       [54, 90, 59],
       [40, 56, 98],
       [61, 25, 38],
       [77, 78, 53]])

In [21]:
#a=1D array, with 7 integer
#b=1D array, with 7 integer
#math operation.

In [22]:
x=random.randint(100, size=(7))
x

array([20, 24, 52, 52, 62, 83, 97])

In [23]:
y=random.randint(50, size=(7))
y

array([19,  7, 46, 36,  1, 21, 12])

In [24]:
x+y

array([ 39,  31,  98,  88,  63, 104, 109])

In [25]:
x-y

array([ 1, 17,  6, 16, 61, 62, 85])

In [26]:
x*y

array([ 380,  168, 2392, 1872,   62, 1743, 1164])

In [27]:
x/y

array([ 1.05263158,  3.42857143,  1.13043478,  1.44444444, 62.        ,
        3.95238095,  8.08333333])

In [28]:
x%y

array([ 1,  3,  6, 16,  0, 20,  1], dtype=int32)

# MATRIX IN NUMPY

In [29]:
a=np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [32]:
a=np.matrix('1 2 3; 4 5 6; 7 8 9')
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
b=np.matrix([[5, 6, 7],[4, 5, 6]])
b

matrix([[5, 6, 7],
        [4, 5, 6]])

# MEASURE OF CENTRAL TENDENCY

In [34]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.amin(arr)

1

In [36]:
np.amax(arr) #max value

9

In [37]:
np.mean(arr)

5.0

In [38]:
np.median(arr)

5.0

In [39]:
np.std(arr) #standard.deviation

2.581988897471611

In [40]:
np.var(arr) #variance

6.666666666666667